name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install .NET 6
        run: bash ./install-net6
      - run: dotnet build SpawnEditor.sln
