name: Windows Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - uses: microsoft/setup-msbuild@v2
      - name: Install Windows Desktop workload
        run: dotnet workload install windowsdesktop
      - run: dotnet build SpawnEditor.sln
